### ISSUE TITLE
Wall Bugs

### ISSUE THREAD

**Issue by SpiralDevs** [fchb1239/FishGame#10]
I was playing **Fish Game** and testing for bugs and **I came across a bug** where **if you went fast enough you could glitch out the wall.** **_I can put gifs below showing what I am talking about below._** **A bug with the tutorial is if you go fast enough you just can phase through the wall.**

Wall Bug:

![fishgamebug2](https://user-images.githubusercontent.com/80377533/142748804-7f6f30e2-b055-40e8-b955-3624405d92c4.gif)

![fishgamebug3](https://user-images.githubusercontent.com/80377533/142748806-4f76925e-da6c-4a65-85d7-d4e23b22356f.gif)

Tutorial Bug:
 ![fishgamebug1](https://user-images.githubusercontent.com/80377533/142748776-6c3c2e3c-d949-43d4-bc61-954c561f48ed.gif)

Also for the tutorial area sometimes when I load up the game it makes me redo not all the time, but I think it's when I turn my Oculus on and off or restart it that it happens.

**Comment by fchb1239** [comment]
unity being funny, it is fixable afaik by just placing bigger collisions outside the maps

**Comment by fchb1239** [comment]
this bug has been fixed a little ago - forgor to say that
